name: PR Check

on:
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5
    
    - name: Setup Node.js
      uses: actions/setup-node@v5
      with:
        node-version: '18'
        
    - name: Install dependencies
      run: npm install
      
    - name: Run lint
      run: npm run lint
      
    - name: Compile
      run: npm run compile
      
    - name: Package
      run: npm run package